run : compil
	java execPack.Main
compil :
	javac  -Xlint:unchecked exceptionPack/*.java execPack/*.java formePack/*.java saisiePack/*.java 
clean :
	rm -f exceptionPack/*.class execPack/*.class formePack/*.class saisiePack/*.class 